import { fakerVI } from '@faker-js/faker';
import { Position } from '@prisma/client';

export function generatePlayerData(clubId: number) {
  const data = [
    {
      name: 'Ngô Tùng Quốc',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_2_NgoTungQuoc_VN001949.jpg',
      position: Position.DEFENDER,
      shirtNumber: 2,
      height: 172,
      weight: 63,
      dateOfBirth: new Date(
        '27-01-1998'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Quế Ngọc Hải',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_3_QueNgocHai_VN001612-1.jpg',
      position: Position.DEFENDER,
      shirtNumber: 3,
      height: 180,
      weight: 77,
      dateOfBirth: new Date(
        '15-05-1993'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Hồ Tấn Tài',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_4_HoTanTai_VN0001223.jpg',
      position: Position.DEFENDER,
      shirtNumber: 4,
      height: 180,
      weight: 77,
      dateOfBirth: new Date(
        '06-11-1997'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Hùng Thiện Đức',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_5_NguyenHungThienDuc_VN002106.jpg',
      position: Position.DEFENDER,
      shirtNumber: 5,
      height: 169,
      weight: 66,
      dateOfBirth: new Date(
        '08-12-1999'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Trần Việt Cường',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_7_NguyenTranVietCuong_VN0001116.jpg',
      position: Position.FORWARD,
      shirtNumber: 7,
      height: 180,
      weight: 68,
      dateOfBirth: new Date(
        '27-12-2000'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Hà Đức Chinh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_9_HaDucChinh_VN001796.jpg',
      position: Position.FORWARD,
      shirtNumber: 9,
      height: 175,
      weight: 74,
      dateOfBirth: new Date(
        '22-09-1997'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Võ Hoàng Minh Khoa',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/BDFC_10_VoHoangMinhKhoa_VN0001118.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 10,
      height: 173,
      weight: 69,
      dateOfBirth: new Date(
        '12-03-2001'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Bùi Vĩ Hào',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/BDFC_11_BuiViHao_VN0001113.jpg',
      position: Position.FORWARD,
      shirtNumber: 11,
      height: 175,
      weight: 68,
      dateOfBirth: new Date(
        '24-02-2003'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Abdurakhmanov Odilzhon Alisherovich',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/BDFC_12_AbdurakhmanovOdilzhonAlisherovich_KG002112.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 12,
      height: 185,
      weight: 80,
      dateOfBirth: new Date(
        '18-03-1996'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Hải Huy',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_14_NguyenHaiHuy_VN001624-1.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 14,
      height: 175,
      weight: 70,
      dateOfBirth: new Date(
        '18-06-1991'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Khắc Vũ',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/03/BDFC_15_NguyenKhacVu_VN001903.jpg',
      position: Position.DEFENDER,
      shirtNumber: 15,
      height: 182,
      weight: 71,
      dateOfBirth: new Date(
        '27-04-1997'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Thành Nhân',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/BDFC_16_NguyenThanhNhan_VN001735.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 16,
      height: 170,
      weight: 68,
      dateOfBirth: new Date(
        '14-04-2000'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Võ Minh Trọng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/BDFC_17_VoMinhTrong_VN0000813.jpg',
      position: Position.DEFENDER,
      shirtNumber: 17,
      height: 170,
      weight: 59,
      dateOfBirth: new Date(
        '24-10-2001'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Ngọc Chiến',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/BDFC_18_NguyenNgocChien_VN002116.jpg',
      position: Position.DEFENDER,
      shirtNumber: 18,
      height: 181,
      weight: 72,
      dateOfBirth: new Date(
        '19-10-2005'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Trần Duy Khánh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/BDFC_19_TranDuyKhanh_VN0001114.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 19,
      height: 172,
      weight: 77,
      dateOfBirth: new Date(
        '20-07-1997'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Đoàn Tuấn Cảnh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_20_DoanTuanCanh_VN001626-1.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 20,
      height: 176,
      weight: 69,
      dateOfBirth: new Date(
        '27-07-1998'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Trần Đình Khương',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_21_TranDinhKhuong_VN0001117-1.jpg',
      position: Position.DEFENDER,
      shirtNumber: 21,
      height: 179,
      weight: 75,
      dateOfBirth: new Date(
        '10-01-1996'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Tiến Linh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_22_NguyenTienLinh_VN001627-1.jpg',
      position: Position.FORWARD,
      shirtNumber: 22,
      height: 181,
      weight: 75,
      dateOfBirth: new Date(
        '20-10-1997'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Vũ Tuyên Quang',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_23_VuTuyenQuang_VN001628-2.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 23,
      height: 185,
      weight: 72,
      dateOfBirth: new Date(
        '05-07-1995'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Trần Hoàng Bảo',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/03/9.-Tran-Hoang-Bao.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 24,
      height: 177,
      weight: 65,
      dateOfBirth: new Date(
        '15-05-2001'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Trần Minh Toàn',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_25_TranMinhToan_VN001630-2.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 25,
      height: 186,
      weight: 85,
      dateOfBirth: new Date(
        '29-01-1996'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Trọng Huy',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/ea886c74-4d11-4bd1-880b-a361f4de89d8.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 26,
      height: 180,
      weight: 74,
      dateOfBirth: new Date(
        '25-06-1997'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Charly Malep DipiTa',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2025/01/8.-Charly-Malep-DipiTa.jpg',
      position: Position.FORWARD,
      shirtNumber: 29,
      height: 189,
      weight: 80,
      dateOfBirth: new Date(
        '17-03-2004'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nguyễn Thành Kiên',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/07/BDFC_33_NguyenThanhKien_VN0001001.jpg',
      position: Position.DEFENDER,
      shirtNumber: 33,
      height: 182,
      weight: 74,
      dateOfBirth: new Date(
        '16-01-2003'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Trần Trung Hiếu',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_39_TranTrungHieu_VN001635.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 39,
      height: 173,
      weight: 80,
      dateOfBirth: new Date(
        '02-02-1993'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Phan Minh Thành',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_46_PhanMinhThanh_VN001636-1.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 46,
      height: 192,
      weight: 80,
      dateOfBirth: new Date(
        '22-11-1998'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Nghiêm Xuân Tú',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/BDFC_77_NghiemXuanTu_VN0000380.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 77,
      height: 174,
      weight: 67,
      dateOfBirth: new Date(
        '28-08-1988'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
    {
      name: 'Janclesio Almeida Santos',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/07/BDFC_93_AlmeidaSantosJanclesio_BR001613.jpg',
      position: Position.DEFENDER,
      shirtNumber: 93,
      height: 190,
      weight: 80,
      dateOfBirth: new Date(
        '22-04-1993'.split('-').reverse().join('-'),
      ).toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
      createdAt: fakerVI.date.recent(),
      updatedAt: fakerVI.date.recent(),
    },
  ];

  return data;
}

export function generatePlayerDataDATH(clubId: number) {
  const data = [
    {
      name: 'Nguyễn Thanh Thắng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_1_NguyenThanhThang_VN002129-310x465.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 1,
      height: 172,
      weight: 65,
      dateOfBirth: new Date('1988-12-14').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Mạnh Hùng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_5_PhamManhHung_VN0001252-310x465.jpg',
      position: Position.DEFENDER,
      shirtNumber: 5,
      height: 178,
      weight: 73,
      dateOfBirth: new Date('1993-03-03').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Igor Salatiel Silva',
      imageURL:
        'https://vpf.vn/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/player_st.png',
      position: Position.DEFENDER,
      shirtNumber: 6,
      height: 192,
      weight: 82,
      dateOfBirth: new Date('2000-01-14').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Thanh Long',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/DATH_7_NguyenThanhLong_VN0001111-310x465.jpg',
      position: Position.DEFENDER,
      shirtNumber: 7,
      height: 180,
      weight: 75,
      dateOfBirth: new Date('1993-01-10').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Võ Nguyên Hoàng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/07/DATH_8_VoNguyenHoang_VN0000556-310x465.jpg',
      position: Position.FORWARD,
      shirtNumber: 8,
      height: 180,
      weight: 78,
      dateOfBirth: new Date('2002-02-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Tùng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2021/03/DATH_9_NguyenVanTung_VN001308-310x465.jpg',
      position: Position.FORWARD,
      shirtNumber: 9,
      height: 168,
      weight: 63,
      dateOfBirth: new Date('2002-03-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Văn Thắng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_10_LeVanThang_VN0001194-3-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 10,
      height: 176,
      weight: 68,
      dateOfBirth: new Date('1990-02-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Thái Sơn',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/THFC_12_NguyenThaiSon_VN001938-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 12,
      height: 171,
      weight: 61,
      dateOfBirth: new Date('2003-07-13').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trương Thanh Nam',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/03/DATH_14_TruongThanhNam_VN001297-310x465.jpg',
      position: Position.DEFENDER,
      shirtNumber: 14,
      height: 172,
      weight: 65,
      dateOfBirth: new Date('2004-04-22').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trịnh Văn Lợi',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_15_TrinhVanLoi_VN0000430-310x465.jpg',
      position: Position.DEFENDER,
      shirtNumber: 15,
      height: 180,
      weight: 71,
      dateOfBirth: new Date('1995-05-26').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lâm Ti Phông',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_17_LamTiPhong_VN0001195-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 17,
      height: 168,
      weight: 65,
      dateOfBirth: new Date('1996-02-01').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đinh Viết Tú',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_18_DinhVietTu_VN0000448-310x465.jpg',
      position: Position.DEFENDER,
      shirtNumber: 18,
      height: 180,
      weight: 78,
      dateOfBirth: new Date('1992-08-16').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Quốc Phương',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_19_LeQuocPhuong_VN0001196-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 19,
      height: 165,
      weight: 61,
      dateOfBirth: new Date('1991-05-19').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lucas Ribamar Lopes dos Santos Bibiano',
      imageURL:
        'https://vpf.vn/wp-content/plugins/joomsport-sports-league-results-management/sportleague/assets/images/player_st.png',
      position: Position.FORWARD,
      shirtNumber: 20,
      height: 184,
      weight: 81,
      dateOfBirth: new Date('1997-05-21').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Trùm Tỉnh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_23_PhamTrumTinh_VN001301-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 23,
      height: 168,
      weight: 62,
      dateOfBirth: new Date('1995-05-02').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Ngọc Mỹ',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/03/DATH_24_NguyenNgocMy_VN002093-310x465.jpg',
      position: Position.FORWARD,
      shirtNumber: 24,
      height: 177,
      weight: 72,
      dateOfBirth: new Date('2004-02-20').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Thanh Diệp',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_25_NguyenThanhDiep_VN0001197-310x465.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 25,
      height: 180,
      weight: 75,
      dateOfBirth: new Date('1991-09-06').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'A Mít',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_27_AMit_VN001303-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 27,
      height: 168,
      weight: 67,
      dateOfBirth: new Date('1997-07-24').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hoàng Thái Bình',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_28_HoangThaiBinh_VN0000282-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 28,
      height: 173,
      weight: 65,
      dateOfBirth: new Date('1998-01-22').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đoàn Ngọc Hà',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_29_DoanNgocHa_VN0000955-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 29,
      height: 182,
      weight: 72,
      dateOfBirth: new Date('2004-02-22').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Y Êli Niê',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_30_YEliNie_VN001304-310x465.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 30,
      height: 182,
      weight: 78,
      dateOfBirth: new Date('2001-01-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Yago Goncalves Nogueira Ramos',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_33_YagoGoncalvesNogueiraRamos_BR002094-310x465.jpg',
      position: Position.FORWARD,
      shirtNumber: 33,
      height: 190,
      weight: 78,
      dateOfBirth: new Date('1996-03-04').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Doãn Ngọc Tân',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_34_DoanNgocTan_VN0000441-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 34,
      height: 169,
      weight: 57,
      dateOfBirth: new Date('1994-08-15').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Bá Tiến',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_45_NguyenBaTien_VN001604-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 45,
      height: 170,
      weight: 65,
      dateOfBirth: new Date('2001-01-19').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Văn Thuận',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_47_LeVanThuan_VN002096-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 47,
      height: 176,
      weight: 61,
      dateOfBirth: new Date('2006-07-15').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hà Châu Phi',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_66_HaChauPhia_VN001583-310x465.jpg',
      position: Position.DEFENDER,
      shirtNumber: 66,
      height: 175,
      weight: 70,
      dateOfBirth: new Date('2003-02-22').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trịnh Xuân Hoàng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_67_TrinhXuanHoang_VN0000436-310x465.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 67,
      height: 184,
      weight: 78,
      dateOfBirth: new Date('2000-11-06').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Luiz Antonio De Souza Soares',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_88_LuizAntonioDeSouzaSoares_BR001306-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 88,
      height: 181,
      weight: 80,
      dateOfBirth: new Date('1991-03-11').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trần Ngọc Quý',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_89_TranNgocQuy_VN002097-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 89,
      height: 181,
      weight: 76,
      dateOfBirth: new Date('2002-03-22').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Gustavo Sant Ana Santos',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/DATH_95_GustavoSantAnaSantos_BR001307-310x465.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 95,
      height: 195,
      weight: 91,
      dateOfBirth: new Date('1995-02-23').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
  ];
  return data;
}

export function generatePlayerDataCAHN(clubId: number) {
  const data = [
    {
      name: 'Filip Nguyen',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/07/CAHN_1_NguyenFilip_VN002118.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 1,
      height: 192,
      weight: 88,
      dateOfBirth: new Date('1992-09-14').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Domingos Gomes Hugo',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/CAHN_3_DomingosGomesHugo_BR002119.jpg',
      position: Position.DEFENDER,
      shirtNumber: 3,
      height: 187,
      weight: 82,
      dateOfBirth: new Date('1995-01-04').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đoàn Văn Hậu',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_5_DoanVanHau_VN0000481.jpg',
      position: Position.DEFENDER,
      shirtNumber: 5,
      height: 185,
      weight: 82,
      dateOfBirth: new Date('1999-04-19').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trương Văn Thiết',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_6_TruongVanThiet_VN0001045-e1725528098243.jpg',
      position: Position.DEFENDER,
      shirtNumber: 6,
      height: 177,
      weight: 68,
      dateOfBirth: new Date('1995-06-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Jason Quang Vinh Pendant',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/CAHN_7_JasonQuangVinhPendant_FR002120.jpg',
      position: Position.DEFENDER,
      shirtNumber: 7,
      height: 177,
      weight: 75,
      dateOfBirth: new Date('1997-02-09').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Rosa Nascimento Vitor Hugo',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/CAHN_8_RosaNascimentoVitorHugo_BR002121.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 8,
      height: 188,
      weight: 83,
      dateOfBirth: new Date('1994-08-12').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Leonardo Artur De Melo',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/10/CAHN_10_LeonardoArturDeMelo_BR002122.jpg',
      position: Position.FORWARD,
      shirtNumber: 10,
      height: 177,
      weight: 68,
      dateOfBirth: new Date('1995-03-23').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Phạm Thành Long',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_11_LePhamThanhLong_VN001901.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 11,
      height: 165,
      weight: 64,
      dateOfBirth: new Date('1996-06-05').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hoàng Văn Toản',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_12_HoangVanToan_VN001902.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 12,
      height: 175,
      weight: 70,
      dateOfBirth: new Date('2001-01-04').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Bùi Xuân Thịnh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2021/03/CAHN_15_BuiXuanThinh_VN0001206.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 15,
      height: 169,
      weight: 64,
      dateOfBirth: new Date('2001-09-15').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Đình Bắc',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/03/CAHN_16_NguyenDinhBac_VN001278-e1725529017160.jpg',
      position: Position.FORWARD,
      shirtNumber: 16,
      height: 179,
      weight: 72,
      dateOfBirth: new Date('2004-08-19').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Vũ Văn Thanh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_17_VuVanThanh_VN001905.jpg',
      position: Position.DEFENDER,
      shirtNumber: 17,
      height: 172,
      weight: 73,
      dateOfBirth: new Date('1996-04-14').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Quang Hải',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_19_NguyenQuangHai_VN0000493.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 19,
      height: 166,
      weight: 65,
      dateOfBirth: new Date('1997-04-12').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phan Văn Đức',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAND_VN0002259_PhanVanDuc_20.png',
      position: Position.MIDFIELDER,
      shirtNumber: 20,
      height: 170,
      weight: 64,
      dateOfBirth: new Date('1996-04-11').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Văn Luân',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_21_PhamVanLuan_VN001908.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 21,
      height: 169,
      weight: 63,
      dateOfBirth: new Date('1999-05-26').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Minh Phúc',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/CAHN_22_PhamMinhPhuc_VN002125.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 22,
      height: 172,
      weight: 64,
      dateOfBirth: new Date('2004-02-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hà Văn Phương',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_26_HaVanPhuong_VN001911.jpg',
      position: Position.DEFENDER,
      shirtNumber: 26,
      height: 170,
      weight: 70,
      dateOfBirth: new Date('2001-07-13').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Đức',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_28_NguyenVanDuc_VN001805.jpg',
      position: Position.DEFENDER,
      shirtNumber: 28,
      height: 168,
      weight: 65,
      dateOfBirth: new Date('1996-01-13').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Trọng Long',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/07/CAHN_88_LeVanDo_VN0000557.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 29,
      height: 170,
      weight: 69,
      dateOfBirth: new Date('2000-01-06').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trần Đình Trọng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_31_TranDinhTrong_VN0000368.jpg',
      position: Position.DEFENDER,
      shirtNumber: 31,
      height: 173,
      weight: 67,
      dateOfBirth: new Date('1997-04-25').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đỗ Sỹ Huy',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_33_DoSyHuy_VN0000772.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 33,
      height: 181,
      weight: 80,
      dateOfBirth: new Date('1998-04-16').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Chu Văn Tấn',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/CAHN_34_ChuVanTan_VN002126.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 34,
      height: 177,
      weight: 80,
      dateOfBirth: new Date('2003-03-24').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hoàng Trung Anh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/09/CAHN_36_HoangTrungAnh_VN002127.jpg',
      position: Position.DEFENDER,
      shirtNumber: 36,
      height: 179,
      weight: 67,
      dateOfBirth: new Date('2004-01-12').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Bùi Hoàng Việt Anh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_68_BuiHoangVietAnh_VN001917.jpg',
      position: Position.DEFENDER,
      shirtNumber: 68,
      height: 184,
      weight: 82,
      dateOfBirth: new Date('1999-01-01').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Alan Sebastiao Alexandre',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/10/CAHN_72_AlanSebastiaoAlexandre_BR002128.jpg',
      position: Position.FORWARD,
      shirtNumber: 72,
      height: 189,
      weight: 84,
      dateOfBirth: new Date('1998-02-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Văn Đô',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/07/CAHN_88_LeVanDo_VN0000557.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 88,
      height: 173,
      weight: 69,
      dateOfBirth: new Date('2001-08-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Giáp Tuấn Dương',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/CAHN_98_GiapTuanDuong_VN001920.jpg',
      position: Position.DEFENDER,
      shirtNumber: 98,
      height: 176,
      weight: 75,
      dateOfBirth: new Date('2002-09-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
  ];
  return data;
}

export function generatePlayerDataHPFC(clubId: number) {
  const data = [
    {
      name: 'Nguyễn Đình Triệu',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_1_NguyenDinhTrieu_VN0000263-1.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 1,
      height: 180,
      weight: 73,
      dateOfBirth: new Date('1991-11-04').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đàm Tiến Dũng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_23_DamTienDung_VN0000424.png',
      position: Position.DEFENDER,
      shirtNumber: 4,
      height: 174,
      weight: 72,
      dateOfBirth: new Date('1996-01-10').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đặng Văn Tới',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_5_DangVanToi_VN0000491.png',
      position: Position.DEFENDER,
      shirtNumber: 5,
      height: 178,
      weight: 74,
      dateOfBirth: new Date('1999-01-12').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Thái Học',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2021/03/HPFC_6_NguyenThaiHoc_VN0000818.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 6,
      height: 170,
      weight: 64,
      dateOfBirth: new Date('2002-01-17').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Tiến Anh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_21_LeTienAnh_VN0000362.png',
      position: Position.MIDFIELDER,
      shirtNumber: 8,
      height: 168,
      weight: 65,
      dateOfBirth: new Date('1998-03-23').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Goncalves Silva Lucas Vinicius',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/08/HPFC_9_GoncalvesSilvaLucasVinicius_BR001679.png',
      position: Position.FORWARD,
      shirtNumber: 9,
      height: 184,
      weight: 79,
      dateOfBirth: new Date('1991-09-14').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Jose Paulo De Oliveira Pinto',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_10_JosePauloDeOliveiraPinto_BR002135.jpg',
      position: Position.FORWARD,
      shirtNumber: 10,
      height: 189,
      weight: 90,
      dateOfBirth: new Date('1994-03-26').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hồ Minh Dĩ',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_11_HoMinhdi_VN0000740.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 11,
      height: 160,
      weight: 58,
      dateOfBirth: new Date('1998-02-17').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trần Vũ Ngọc Tài',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/07/HPFC_12_TranVuNgocTai_VN0000992.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 12,
      height: 172,
      weight: 65,
      dateOfBirth: new Date('2004-01-25').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Ngọc Tú',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/HPFC_15_NguyenNgocTu_VN001478-1.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 15,
      height: 170,
      weight: 68,
      dateOfBirth: new Date('2002-02-15').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Bùi Tiến Dụng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/HPFC_16_BuiTienDung_VN0001218.jpg',
      position: Position.DEFENDER,
      shirtNumber: 16,
      height: 176,
      weight: 76,
      dateOfBirth: new Date('1998-11-23').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Trung Hiếu',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/HPFC_VN0002252_PhamTrungHieu_17.jpg',
      position: Position.DEFENDER,
      shirtNumber: 17,
      height: 169,
      weight: 65,
      dateOfBirth: new Date('1998-09-02').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Mạnh Dũng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/HPFC_VN0002242_LeManhDung_19.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 19,
      height: 172,
      weight: 70,
      dateOfBirth: new Date('1994-02-10').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Miche Naider Chery',
      imageURL: 'https://vpf.vn/wp-content/uploads/2025/01/Miche.jpg',
      position: Position.FORWARD,
      shirtNumber: 20,
      height: 186,
      weight: 78,
      dateOfBirth: new Date('1997-11-13').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Ngô Văn Bắc',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/SLNA_27_NgoVanBac_VN001835.jpg',
      position: Position.DEFENDER,
      shirtNumber: 21,
      height: 169,
      weight: 63,
      dateOfBirth: new Date('2004-03-27').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Ngọc',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/03/HPFC_23_NguyenVanNgoc_VN0000749.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 23,
      height: 175,
      weight: 67,
      dateOfBirth: new Date('1999-01-05').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Toản',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/02/HPFC_26_NguyenVanToan_VN0000281-1.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 26,
      height: 186,
      weight: 80,
      dateOfBirth: new Date('1999-11-26').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Nhật Minh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/HPFC_27_NguyenNha_tMinh_VN0000576.png',
      position: Position.DEFENDER,
      shirtNumber: 27,
      height: 175,
      weight: 65,
      dateOfBirth: new Date('2003-07-27').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Minh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/04/HPFC_VN0000488_NguyenVanMinh_29.png',
      position: Position.DEFENDER,
      shirtNumber: 29,
      height: 169,
      weight: 58,
      dateOfBirth: new Date('1999-02-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lương Hoàng Nam',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_30_LuongHoangNam_VN0001246.png',
      position: Position.MIDFIELDER,
      shirtNumber: 30,
      height: 160,
      weight: 57,
      dateOfBirth: new Date('1997-03-02').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Văn Luân',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/HPFC_VN0002249_PhamVanLuan_25.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 36,
      height: 177,
      weight: 73,
      dateOfBirth: new Date('1994-07-12').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Trọng Hiếu',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/03/HPFC_38_NguyenTrongHieu_VN0000265.jpg',
      position: Position.DEFENDER,
      shirtNumber: 38,
      height: 180,
      weight: 77,
      dateOfBirth: new Date('2001-01-17').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Thành Đồng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_45_NguyenThanhDong_VN001683.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 45,
      height: 170,
      weight: 65,
      dateOfBirth: new Date('1995-02-06').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Duy Kiên',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2019/04/HPFC_56_NguyenDuyKien_VN0000743-1.jpg',
      position: Position.DEFENDER,
      shirtNumber: 56,
      height: 175,
      weight: 67,
      dateOfBirth: new Date('2000-11-23').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Thành Long',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/03/z6240246938871_67ae29c4eb718e92398b836212319c10.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 58,
      height: 175,
      weight: 70,
      dateOfBirth: new Date('2005-06-20').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Hữu Sơn',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/HPFC_VN0002255_NguyenHuuSon_77.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 77,
      height: 172,
      weight: 65,
      dateOfBirth: new Date('1996-09-27').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Tuấn Anh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_79_NguyenTuanAnh_VN001684.png',
      position: Position.MIDFIELDER,
      shirtNumber: 79,
      height: 171,
      weight: 61,
      dateOfBirth: new Date('1999-07-07').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Tú',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/03/HPFC_88_NguyenVanTu_VN001499.png',
      position: Position.MIDFIELDER,
      shirtNumber: 88,
      height: 176,
      weight: 70,
      dateOfBirth: new Date('2003-01-17').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Triệu Việt Hưng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2020/01/HPFC_97_TrieuVietHung_VN0000287.jpg',
      position: Position.DEFENDER,
      shirtNumber: 97,
      height: 171,
      weight: 70,
      dateOfBirth: new Date('1997-01-19').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
  ];
  return data;
}

export function generatePlayerDataSLNA(clubId: number) {
  const data = [
    {
      name: 'Nguyễn Văn Việt',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_1_NguyenVanViet_VN0001172.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 1,
      height: 180,
      weight: 70,
      dateOfBirth: new Date('2002-07-12').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Vương Văn Huy',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_2_VuongVanHuy_VN0001173.jpg',
      position: Position.DEFENDER,
      shirtNumber: 2,
      height: 163,
      weight: 63,
      dateOfBirth: new Date('2001-08-10').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Nguyên Hoàng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_3_LeNguyenHoang_VN001815.jpg',
      position: Position.DEFENDER,
      shirtNumber: 3,
      height: 177,
      weight: 68,
      dateOfBirth: new Date('2005-02-14').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hồ Khắc Lương',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_4_HoKhacLuong_VN0001186.jpg',
      position: Position.DEFENDER,
      shirtNumber: 4,
      height: 172,
      weight: 68,
      dateOfBirth: new Date('2001-01-10').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Văn Thành',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_5_LeVanThanh_VN0001176.jpg',
      position: Position.DEFENDER,
      shirtNumber: 5,
      height: 177,
      weight: 68,
      dateOfBirth: new Date('2001-07-24').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trần Đình Hoàng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_6_TranDinhHoang_VN0001189.jpg',
      position: Position.DEFENDER,
      shirtNumber: 6,
      height: 174,
      weight: 68,
      dateOfBirth: new Date('1991-12-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Olaha Michael Onyedikachi',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_7_OlahaMichaelOnyedikachi_NG002186.jpg',
      position: Position.FORWARD,
      shirtNumber: 7,
      height: 180,
      weight: 78,
      dateOfBirth: new Date('1997-07-04').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hồ Văn Cường',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_8_HoVanCuong_VN001640.jpg',
      position: Position.DEFENDER,
      shirtNumber: 8,
      height: 167,
      weight: 63,
      dateOfBirth: new Date('2003-01-15').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đinh Xuân Tiến',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_9_DinhXuanTien_VN0001185.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 9,
      height: 171,
      weight: 65,
      dateOfBirth: new Date('2003-01-10').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Benjamin Thomas Kuku',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_10_BenjaminThomasKuku_NG002188.jpg',
      position: Position.FORWARD,
      shirtNumber: 10,
      height: 190,
      weight: 92,
      dateOfBirth: new Date('1995-03-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trần Mạnh Quỳnh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_11_TranManhQuynh_VN001824.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 11,
      height: 170,
      weight: 65,
      dateOfBirth: new Date('2001-01-18').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Bùi Thanh Đức',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_12_BuiThanhDuc_VN002052.jpg',
      position: Position.DEFENDER,
      shirtNumber: 12,
      height: 173,
      weight: 62,
      dateOfBirth: new Date('06/03/2006').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phùng Văn Nam',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_13_PhungVanNam_VN002190.jpg',
      position: Position.FORWARD,
      shirtNumber: 13,
      height: 173,
      weight: 60,
      dateOfBirth: new Date('2006-01-22').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Trọng Tuấn',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_14_NguyenTrongTuan_VN002191.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 14,
      height: 178,
      weight: 76,
      dateOfBirth: new Date('2006-01-18').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Eduardo Sebastian Zaracho Espinola',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_15_EduardoSebastianZarachoEspinola_PY002192.jpg',
      position: Position.DEFENDER,
      shirtNumber: 15,
      height: 186,
      weight: 74,
      dateOfBirth: new Date('1999-01-20').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Quang Vinh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_16_NguyenQuangVinh_VN001830.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 16,
      height: 174,
      weight: 68,
      dateOfBirth: new Date('2005-01-27').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Trần Nam Hải',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/SLNA_17_TranNamHai_VN0000999.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 17,
      height: 182,
      weight: 75,
      dateOfBirth: new Date('2004-02-05').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phan Bá Quyền',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/SLNA_19_PhanBaQuyen_VN001831.jpg',
      position: Position.DEFENDER,
      shirtNumber: 19,
      height: 175,
      weight: 68,
      dateOfBirth: new Date('2002-02-17').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Ngô Văn Lương',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_20_NgoVanLuong_VN0001183.jpg',
      position: Position.FORWARD,
      shirtNumber: 20,
      height: 172,
      weight: 65,
      dateOfBirth: new Date('2001-06-03').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phan Xuân Đại',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_21_PhanXuanDai_VN0001184.jpg',
      position: Position.FORWARD,
      shirtNumber: 21,
      height: 173,
      weight: 65,
      dateOfBirth: new Date('2003-01-01').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Mai Hoàng',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_23_NguyenMaiHoang_VN002193.jpg',
      position: Position.DEFENDER,
      shirtNumber: 23,
      height: 174,
      weight: 65,
      dateOfBirth: new Date('2005-02-21').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Hữu Hậu',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_25_NguyenHuuHau_VN002194.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 25,
      height: 183,
      weight: 75,
      dateOfBirth: new Date('2004-04-19').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Cao Văn Bình',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_26_CaoVanBinh_VN001834.jpg',
      position: Position.GOALKEEPER,
      shirtNumber: 26,
      height: 183,
      weight: 80,
      dateOfBirth: new Date('2005-01-08').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phạm Nguyễn Quốc Trung',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_27_PhamNguyenQuocTrung_VN002195.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 27,
      height: 171,
      weight: 65,
      dateOfBirth: new Date('2006-05-06').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Nguyễn Văn Bách',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2023/01/SLNA_28_NguyenVanBach_VN0000404.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 28,
      height: 172,
      weight: 66,
      dateOfBirth: new Date('2003-01-02').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Đặng Quang Tú',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2022/02/SLNA_29_DangQuangTu_VN001836.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 29,
      height: 173,
      weight: 69,
      dateOfBirth: new Date('13/06/2001').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hồ Khắc Ngọc',
      imageURL: 'https://vpf.vn/wp-content/uploads/2018/12/2.-Ho-Khac-Ngoc.jpg',
      position: Position.MIDFIELDER,
      shirtNumber: 32,
      height: 170,
      weight: 60,
      dateOfBirth: new Date('1992-08-02').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Phan Văn Thành',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/03/40.-Phan-Van-Thanh.jpg',
      position: Position.DEFENDER,
      shirtNumber: 33,
      height: 183,
      weight: 70,
      dateOfBirth: new Date('2006-06-27').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Lê Đình Long Vũ',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2024/03/39.-Le-Dinh-Long-Vu.jpg',
      position: Position.FORWARD,
      shirtNumber: 38,
      height: 172,
      weight: 65,
      dateOfBirth: new Date('2006-05-27').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
    {
      name: 'Hoàng Văn Khánh',
      imageURL:
        'https://vpf.vn/wp-content/uploads/2018/12/1.-Hoang-Van-Khanh.jpg',
      position: Position.DEFENDER,
      shirtNumber: 55,
      height: 181,
      weight: 71,
      dateOfBirth: new Date('1995-04-05').toISOString(),
      nationality: 'Việt Nam',
      clubId: clubId,
    },
  ];
  return data;
}
